import Banner from '@/components/Banner'
import Header from '@/components/Header'
import '@/styles/globals.css'
import React from 'react'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) : React.ReactNode{
  return (
    <html>
      <body className="max-w-7xl mx-auto">
        <Header />
        <Banner></Banner>
        {children}
      </body>
    </html>
  )
}
